-- order by é utilizado para ordenar os resultados de uma consulta

SELECT * FROM itens ORDER BY nome; -- ME TRAS TODOS OS DADOS ORDENADOS PELO NOME
SELECT * FROM itens ORDER BY nome DESC; -- ME TRAS TODOS OS DADOS ORDENADOS PELO NOME DE FORMA DESCENDENTE
SELECT * FROM itens ORDER BY nome ASC; -- ME TRAS TODOS OS DADOS ORDENADOS PELO NOME DE FORMA ASCENDENTE